on:
  # - push
  - pull_request

name: Main

jobs:
  pre-commit:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.7'
      - run: |
          pip install pre-commit
          dotnet tool install -g dotnet-format
          pre-commit run --all-files --show-diff-on-failure

  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          dotnet test tests

  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          pip install invoke pyyaml
          invoke build

          mkdir tmp
          curl -L -O https://github.com/JosefNemec/Playnite/releases/download/10.12/Playnite1012.zip
          unzip Playnite1012.zip -d tmp/playnite

          invoke pack --toolbox ./tmp/playnite/Toolbox.exe

      - uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            dist/*.pext
            dist/*.zip
